* [ ] Replace edit icon with pencil
* [ ] Current day should be styled differently
* [ ] If removing name/string of todo, it should delete it from the list.
* [ ] remove unecessary id from todo model
* [ ] clicking on viewTodoEmpty should focus viewTodoNew
* [ ] clicking outside input should set editing to false
* [ ] Feature: Drag and Drop
* [ ] Feature: Future Weeks 
* [ ] Feature: Previous Todo's roll over
* [ ] Feature: Generic Lists at the bottom
* [X] Create stack of todo entries up to N max per day.
CLOSED: [2018-06-26 Tue 22:34]
* [X] Create Todo
CLOSED: [2018-06-26 Tue 19:28]
- controlled inputs : dict> key date | value: input

  
* Notes
** Comparable Dict.fromList 
interesting: https://github.com/elm/compiler/issues/774
  - ran into this  when trying to map over a list of DAYs but it wouldn't let me
    do a Dict.fromList because Day wasn't comparable.
    #+BEGIN_QUOTE
    We've run into this a lot with validation errors.

Specifically we want to enumerate all the fields on a form as a union type (e.g. type Field = Username | Password | Email), and then to represent validation errors as a Dict Field String so we can easily look up whether there is an error on a given field with things like Dict.get.

We work around this by using List (Field, String) as a fake Dict and then filter it a lot. You can see a public example of where we're doing this here: http://package.elm-lang.org/packages/NoRedInk/elm-rails/1.1.0/Rails-Decode - we'd definitely prefer if that function had the following signature:

errors : Dict String comparable -> Decoder (Dict comparable (List String))
Right now we can't do that, because if we did we couldn't use union types for our fields.
    #+END_QUOTE

* Links
- [[http://package.elm-lang.org/packages/elm-lang/core/5.1.1/Date][elm core date]]
- [[https://stackoverflow.com/questions/37910613/how-do-i-get-the-current-date-in-elm][get current date in elm]]
- [[https://github.com/evancz/elm-todomvc/blob/master/Todo.elm][elm todo mvc (of course)]]
